/* GORILLA BOOMIN — OFFICIAL ARTIST BRAND POLISH */
(function(){
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const hero=$('.hero-v5');
  if(!hero) return;

  if(!document.querySelector('link[href^="dream.css"]')){
    const css=document.createElement('link');css.rel='stylesheet';css.href='dream.css?v=9';document.head.appendChild(css);
  }

  if(!$('#brand-v9-styles')){
    const st=document.createElement('style');st.id='brand-v9-styles';st.textContent=`
      :root{--gb-gold:#e7b84d;--gb-silver:#d8dde5;--gb-black:#050508}
      .brand>span:last-child small{display:none!important}.brand>span:last-child{letter-spacing:.5px}
      .hero-pro strong{display:none!important}.hero-pro{color:#fff!important}
      .hero-topline{display:flex!important;align-items:center!important;gap:10px!important;flex-wrap:wrap!important;white-space:normal!important}
      .hero-topline .country-chip{display:inline-flex;align-items:center;gap:6px;padding:6px 9px;border:1px solid #ffffff24;background:#050509a8;backdrop-filter:blur(8px)}
      .hero-topline .country-x{color:var(--gb-gold);font-weight:900}
      .brand-signature-v9{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:18px 0 0;max-width:760px}
      .brand-signature-v9 span{padding:8px 10px;border:1px solid #ffffff20;background:#07070bcf;color:#fff;font:800 8px Orbitron;letter-spacing:1.7px}
      .brand-signature-v9 span:nth-child(1){border-color:#e7b84d66}.brand-signature-v9 span:nth-child(2){border-color:#d8dde566}.brand-signature-v9 span:nth-child(3){border-color:#ff2ca866}
      .official-socials-v9{margin-top:34px;padding-top:22px;border-top:1px solid #ffffff16}
      .official-socials-v9 .social-title{font:800 9px Orbitron;letter-spacing:3px;color:#8e94a3;margin-bottom:13px}
      .official-socials-v9 .social-row{display:flex;gap:9px;flex-wrap:wrap}
      .official-socials-v9 a{display:inline-flex;align-items:center;gap:7px;padding:10px 12px;border:1px solid #ffffff20;background:#0a0a10;color:#fff;text-decoration:none;font:800 8px Orbitron;letter-spacing:1.2px;transition:.2s}
      .official-socials-v9 a:hover{border-color:#e7b84d88;transform:translateY(-2px)}
      .next-chapter h2 em,.release-copy h2 em{background:linear-gradient(90deg,#f1f4f8 0%,#b9c0ca 35%,#f0c657 70%,#c5912d 100%);-webkit-background-clip:text;background-clip:text;color:transparent!important}
      .brand-motto-v9{margin:18px 0 24px;font:900 clamp(14px,1.5vw,21px) Orbitron;letter-spacing:2px;color:#fff;line-height:1.55}
      .brand-motto-v9 b{color:var(--gb-gold)}
      @media(max-width:700px){
        .hero-topline{font-size:10px!important;gap:6px!important}
        .hero-topline .country-chip{padding:5px 7px!important}
        .hero-topline .country-x{padding:0 1px}
        .brand-signature-v9{gap:6px}.brand-signature-v9 span{font-size:7px;letter-spacing:1px;padding:7px 8px}
        .hero-still-main{background-position:35% 18%!important;transform:scale(1.16)!important;filter:saturate(.94) contrast(1.05) brightness(.58)!important}
        .hero-still-v7:after{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(90deg,rgba(3,3,7,.92) 0%,rgba(3,3,7,.74) 47%,rgba(3,3,7,.48) 72%,rgba(3,3,7,.72) 100%),linear-gradient(0deg,rgba(3,3,7,.82) 0%,transparent 55%);z-index:1}
        .hero-v5-copy{z-index:3!important}
      }
      @media(max-width:520px){
        .hero-topline{justify-content:flex-start!important;max-width:calc(100vw - 40px)!important;gap:4px!important}
        .hero-topline .country-chip{padding:5px 7px!important;font-size:clamp(8px,2.45vw,10px)!important;letter-spacing:.65px!important;min-height:28px;box-sizing:border-box;background:#07070bdc;border-color:#ffffff1f}
        .hero-topline .country-x{font-size:10px!important;padding:0 2px!important}
        .hero-pro{font-size:clamp(13px,4vw,18px)!important}
        .hero-v5-lead{font-size:10px!important}.brand-signature-v9{max-width:100%}.brand-signature-v9 span{flex:1 1 auto;text-align:center}
        .hero-still-main{background-position:30% 20%!important;transform:scale(1.22)!important;filter:saturate(.9) contrast(1.06) brightness(.5)!important}
        .hero-still-v7:after{background:linear-gradient(90deg,rgba(3,3,7,.96) 0%,rgba(3,3,7,.82) 54%,rgba(3,3,7,.58) 76%,rgba(3,3,7,.78) 100%),linear-gradient(0deg,rgba(3,3,7,.9) 0%,rgba(3,3,7,.2) 60%,rgba(3,3,7,.45) 100%)}
        .stage-flags{display:grid!important;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr)!important;width:100%;gap:4px!important;align-items:stretch!important}
        .stage-flags span{font-size:7px!important;letter-spacing:.35px!important;padding:7px 4px!important;text-align:center!important;display:flex!important;align-items:center!important;justify-content:center!important;min-height:30px;box-sizing:border-box;background:#08080dd9!important}
        .stage-flags span:nth-child(2){min-width:26px!important;padding-inline:2px!important}
        .stage-flags span:last-child{grid-column:1/-1;min-height:26px!important;padding-block:5px!important}
      }
    `;document.head.appendChild(st);
  }

  document.title='Lee Dominique Viarruel | GORILLA BOOMIN — DJ, Producer & Pan Fusion Tech House Artist';
  const meta=document.querySelector('meta[name="description"]');
  if(meta) meta.content='Official website of Lee Dominique Viarruel, professionally known as GORILLA BOOMIN — DJ, producer, singer, live artist and steelpan performer creating Pan Fusion Tech House from Trinidad & Tobago to Romania and the global stage.';
  let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=location.origin+location.pathname;
  if(!$('#gb-schema')){const schema=document.createElement('script');schema.id='gb-schema';schema.type='application/ld+json';schema.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Person',name:'Lee Dominique Viarruel',alternateName:'GORILLA BOOMIN',jobTitle:['DJ','Music Producer','Singer','Live Artist','Steelpan Artist','Songwriter'],description:'Trinidad & Tobago-born artist, DJ, producer, singer and steelpan performer developing Pan Fusion Tech House from Romania for the global stage.',sameAs:['https://www.youtube.com/@GorillaBoomin','https://www.instagram.com/gorillaboomin','https://www.tiktok.com/@gorilla.boomin','https://www.facebook.com/GorillaBoomin'],knowsAbout:['Pan Fusion Tech House','Electronic Dance Music','Steelpan','Music Production','Live Performance']});document.head.appendChild(schema);}

  const brand=$('.brand');if(brand){const t=brand.querySelector('span:last-child');if(t)t.innerHTML='GORILLA <b>BOOMIN</b>';}
  $$('.top-marquee span').forEach(el=>{el.textContent=el.textContent.replace(/GORILLA BOOMIN PRO/gi,'GORILLA BOOMIN').replace(/PAN FUSION(?! TECH HOUSE)/gi,'PAN FUSION TECH HOUSE')});
  const ticker=$('.ticker');if(ticker)ticker.textContent=ticker.textContent.replace(/GORILLA BOOMIN PRO/gi,'GORILLA BOOMIN').replace(/PAN FUSION(?! TECH HOUSE)/gi,'PAN FUSION TECH HOUSE');

  const heroTop=$('.hero-topline');if(heroTop)heroTop.innerHTML='<span class="country-chip">🇹🇹 TRINIDAD &amp; TOBAGO</span><span class="country-x">×</span><span class="country-chip">🇷🇴 ROMANIA</span>';
  const heroPro=$('.hero-pro');if(heroPro)heroPro.textContent='GORILLA BOOMIN';
  const lead=$('.hero-v5-lead');if(lead)lead.textContent='DJ • PRODUCER • SINGER • LIVE ARTIST • STEELPAN • PAN FUSION TECH HOUSE';
  if(!$('.brand-signature-v9')){const sig=document.createElement('div');sig.className='brand-signature-v9';sig.innerHTML='<span>DIFFERENT SOUND.</span><span>DIFFERENT ENERGY.</span><span>DIFFERENT ANIMAL.</span>';const actions=$('.hero-actions');if(actions)actions.insertAdjacentElement('afterend',sig);}
  const cap=$('.hero-v5-caption');if(cap){cap.innerHTML='<span>GORILLA BOOMIN</span><span>DJ • PRODUCER • SINGER • LIVE ARTIST • PAN FUSION TECH HOUSE</span>';}

  const heroCinema=$('.hero-cinema');if(heroCinema&&!$('.hero-still-v7')){heroCinema.innerHTML=`<div class="hero-still-v7" role="img" aria-label="Gorilla Boomin artist, DJ and live performance world"><div class="hero-still-main"></div><div class="hero-still-cut hero-still-cut-a"></div><div class="hero-still-cut hero-still-cut-b"></div></div><div class="cinema-fallback"></div>`;}

  let live=$('#djlive');
  if(!live){live=document.createElement('section');live.id='djlive';live.className='next-chapter';live.innerHTML=`<div class="next-chapter-media" aria-hidden="true"><video autoplay muted loop playsinline preload="metadata" poster="assets/hero-festival-poster.jpg"><source src="assets/hero-festival.mp4" type="video/mp4"></video></div><div class="next-chapter-copy"><div class="next-kicker">THE NEXT CHAPTER / LIVE</div><h2>DJ. PRODUCER.<br><em>LIVE ARTIST.</em></h2><div class="next-tagline">CARIBBEAN ROOTS. GLOBAL STAGE. <strong>FUTURE SOUND.</strong></div><div class="next-sound">PAN FUSION TECH HOUSE</div><p class="next-body">Singer. Steelpan artist. DJ. Producer. One live identity built from Caribbean rhythm, stage experience and electronic music designed for the drop.</p><div class="brand-motto-v9">DIFFERENT SOUND. <b>DIFFERENT ENERGY.</b> DIFFERENT ANIMAL.</div><div class="vision-line"><span>REAL HISTORY</span><b>→</b><span>NEW SOUND</span><b>→</b><span>MAIN STAGE</span></div><div class="next-actions"><a class="btn" href="#mediahub">WATCH / LISTEN</a><a class="btn ghost" href="#contact">BOOK GORILLA BOOMIN</a></div><div class="stage-flags"><span class="tt">🇹🇹 TRINIDAD &amp; TOBAGO</span><span>×</span><span class="ro">🇷🇴 ROMANIA</span><span>• WORLDWIDE</span></div></div>`;hero.insertAdjacentElement('afterend',live);const divider=document.createElement('div');divider.className='festival-divider';live.insertAdjacentElement('afterend',divider);}
  else{const body=live.querySelector('.next-body');if(body)body.textContent='Singer. Steelpan artist. DJ. Producer. One live identity built from Caribbean rhythm, stage experience and electronic music designed for the drop.';if(!live.querySelector('.brand-motto-v9')){const motto=document.createElement('div');motto.className='brand-motto-v9';motto.innerHTML='DIFFERENT SOUND. <b>DIFFERENT ENERGY.</b> DIFFERENT ANIMAL.';const vision=live.querySelector('.vision-line');if(vision)vision.insertAdjacentElement('beforebegin',motto);}}

  let release=$('#newmusic');
  if(!release){const divider=$('.festival-divider');release=document.createElement('section');release.id='newmusic';release.className='release-billboard festival-section';release.innerHTML=`<div class="release-wrap"><div class="release-art"><img src="assets/ChatGPT%20Image%20Aug%2020,%202026,%2004_58_59%20AM.png" alt="Gorilla Boomin upcoming release artwork placeholder"><span>NEW MUSIC</span></div><div class="release-copy"><div class="release-kicker">GORILLA BOOMIN / NEXT RELEASE</div><div class="release-status">COMING SOON</div><h2>THE NEXT<br><em>DROP.</em></h2><div class="release-artist">GORILLA BOOMIN</div><div class="release-genre">PAN FUSION TECH HOUSE</div><p>New music is being built now. This official release window is ready for the real cover, title, date and streaming links when the next Gorilla Boomin record drops.</p><div class="release-actions"><a class="btn gold" href="#mediahub">LISTEN / WATCH</a><a class="btn ghost" href="#contact">GET RELEASE UPDATES</a></div><small>ARTWORK • TITLE • RELEASE DATE • STREAMING LINKS — READY TO ACTIVATE</small></div></div>`;if(divider)divider.insertAdjacentElement('afterend',release);}

  const nav=$('#mainNav');if(nav&&!nav.querySelector('a[href="#djlive"]')){const a=document.createElement('a');a.href='#djlive';a.textContent='DJ / LIVE';const worlds=nav.querySelector('a[href="#worlds"]');worlds?nav.insertBefore(a,worlds):nav.prepend(a);}if(nav&&!nav.querySelector('a[href="#newmusic"]')){const a=document.createElement('a');a.href='#newmusic';a.textContent='NEW MUSIC';const worlds=nav.querySelector('a[href="#worlds"]');worlds?nav.insertBefore(a,worlds):nav.appendChild(a);}

  const storyTitle=$('.story-title');if(storyTitle){const h2=storyTitle.querySelector('h2');if(h2)h2.innerHTML='LEE DOMINIQUE<br><em>VIARRUEL.</em>';const sign=storyTitle.querySelector('.story-sign');if(sign)sign.innerHTML='<strong>PROFESSIONALLY KNOWN AS GORILLA BOOMIN</strong><br>DJ • PRODUCER • SINGER • LIVE ARTIST • STEELPAN';const portrait=storyTitle.querySelector('.story-portrait-v6 img');if(portrait){portrait.src='assets/Skylight.jpg';portrait.alt='Lee Dominique Viarruel — professionally known as Gorilla Boomin';}if(!storyTitle.querySelector('.bio-identity-v7')){const badge=document.createElement('div');badge.className='bio-identity-v7';badge.innerHTML='<span>THE ARTIST</span><b>GORILLA BOOMIN</b><small>PAN FUSION TECH HOUSE • DJ / PRODUCER • SINGER • LIVE ARTIST</small>';storyTitle.appendChild(badge);}}

  const storyCopy=$('.story-copy-v5');if(storyCopy){storyCopy.innerHTML=`<p class="story-lead"><strong>Lee Dominique Viarruel</strong>, professionally known as <strong>GORILLA BOOMIN</strong>, is a Trinidad &amp; Tobago-born singer, steelpan artist, songwriter, DJ and producer building his next chapter from Romania.</p><div class="bio-chapter-v7"><span>01</span><b>ROOTS &amp; IDENTITY</b></div><p>Music entered his life early. Performing from age 11, Lee developed first as a vocalist and entertainer while steelpan became one of the signatures of his musical identity. His pan journey included personal training and mentorship from Ken “Professor” Philmore and Len “Boogsie” Sharpe.</p><div class="bio-chapter-v7"><span>02</span><b>THE WORLD STAGE</b></div><p>His career expanded internationally through bands, hotels, resorts, casinos and cruise ships, followed by seven years in Japan performing as a singer, dancer and musician with J.J. Renaude’s Body &amp; Soul Show Group of Australia in Tokyo and Kamogawa, Chiba.</p><p>Along the way he performed in productions and shared stages or musical spaces with artists including <strong>Shaggy, Rihanna, Machel Montano, Kes, David Rudder and Super Blue.</strong></p><div class="bio-chapter-v7"><span>03</span><b>THE DJ AWAKENING</b></div><p>Cruise-ship life around Miami and the Bahamas opened another door: DJs, clubs and electronic dance music. That world reshaped the vision — combining the instinct of a live entertainer with the control, energy and scale of modern electronic production.</p><div class="bio-chapter-v7"><span>04</span><b>PAN FUSION TECH HOUSE</b></div><p>Today the focus is <strong>Pan Fusion Tech House</strong>: Caribbean soul meeting club and festival energy. Steelpan can become the hook, texture, melody or drop, fused with Tech House, Latin Tech, Afro House, Dancehall, Soca and future-facing electronic production.</p><div class="bio-chapter-v7"><span>05</span><b>THE NEXT CHAPTER</b></div><p>After stepping away from new music for years, Lee is building again with <strong>DJ / Producer</strong> at the front of the mission while keeping his singer and live-steelpan identity intact. <strong>BOOM STUDIO!</strong> is the production world, <strong>xXGorillaBoominXx</strong> is the gaming world, and <strong>GORILLA BOOMIN</strong> is the artist connecting it all.</p><blockquote>“To make a huge difference in the world through my music.”</blockquote>`;}

  const yt=$('.youtube-player');if(yt){yt.innerHTML=`<div class="player-top"><span>GORILLA BOOMIN / YOUTUBE</span><span>@GORILLABOOMIN</span></div><div class="dream-live-video"><video controls playsinline preload="metadata"><source src="assets/GORILLA%20BOOMIN%20performs%20(Big%20People%20Party).mp4" type="video/mp4"></video></div><div class="yt-caption"><strong>OFFICIAL ARTIST CHANNEL.</strong> Live performances, DJ / producer content, steelpan, vocals, studio sessions and the Pan Fusion Tech House journey. <a href="https://www.youtube.com/@GorillaBoomin" target="_blank" rel="noopener">OPEN YOUTUBE ↗</a></div>`;}

  const media=$('#media'),archiveGrid=$('#archiveGrid');if(media&&archiveGrid&&!media.querySelector('.performance-showcase-v8')){const showcase=document.createElement('div');showcase.className='performance-showcase-v8';showcase.innerHTML=`<article class="performance-card-v8"><div class="performance-video-v8"><video controls playsinline preload="metadata"><source src="assets/Gorilla%20Boomin%20Performs%20(Old%20School%20Soca%20Medley)%20at%20MMM%20Concert.mp4" type="video/mp4"></video></div><div class="performance-copy-v8"><span>WORLD STAGE / LIVE ARCHIVE</span><h3>OLD SCHOOL SOCA MEDLEY</h3><p>Concert footage that captures the entertainer behind the brand — live vocals, stage command and Caribbean performance roots.</p></div></article><article class="performance-card-v8"><div class="performance-video-v8"><video controls playsinline preload="metadata"><source src="assets/GORILLA%20BOOMIN%20performs%20(Big%20People%20Party).mp4" type="video/mp4"></video></div><div class="performance-copy-v8"><span>MEDIA / PERFORMANCE ARCHIVE</span><h3>BIG PEOPLE PARTY</h3><p>A clear live-performance chapter from the journey — vocals, movement and real stage energy on the road to Gorilla Boomin.</p></div></article>`;archiveGrid.insertAdjacentElement('beforebegin',showcase);}
  const archiveIntro=$('#media .section-intro');if(archiveIntro)archiveIntro.textContent='A career told through real moments — stages, steelpan, cruise ships, media, DJ evolution, performances and the road into the next chapter.';const now=$('.media-now');if(now)now.innerHTML='<span class="dot"></span> NOW PLAYING / PAN FUSION TECH HOUSE';

  document.querySelectorAll('.world-tech-v51 span,.track-info strong').forEach(el=>{if(/PAN FUSION(?! TECH HOUSE)/i.test(el.textContent))el.textContent=el.textContent.replace(/PAN FUSION(?! TECH HOUSE)/gi,'PAN FUSION TECH HOUSE');});
  const soundHeading=$('#music h2');if(soundHeading)soundHeading.innerHTML='PAN FUSION<br><em>TECH HOUSE.</em>';
  const featureArt=$('#music .feature-art');if(featureArt)featureArt.alt='Pan Fusion Tech House artwork';
  const networkCards=$$('#network article');networkCards.forEach(card=>{const title=card.querySelector('b');if(title&&/GORILLA BOOMIN PRO/i.test(title.textContent)){title.textContent='GORILLA BOOMIN HQ';const p=card.querySelector('p');if(p)p.textContent='The official digital headquarters connecting the artist, BOOM STUDIO!, music, bookings, media and gaming.';}if(title&&/VST SPOT/i.test(title.textContent)){title.textContent='SAMPLE PACKS';const p=card.querySelector('p');if(p)p.textContent='Future BOOM STUDIO packs for steelpan loops, Caribbean percussion, vocal chops, drum loops, FX and one-shots.';}});

  const contact=$('#contact');if(contact&&!contact.querySelector('.official-socials-v9')){const links=document.createElement('div');links.className='official-socials-v9';links.innerHTML=`<div class="social-title">OFFICIAL GORILLA BOOMIN LINKS</div><div class="social-row"><a href="https://www.youtube.com/@GorillaBoomin" target="_blank" rel="noopener">▶ YOUTUBE</a><a href="https://www.instagram.com/gorillaboomin" target="_blank" rel="noopener">◎ INSTAGRAM</a><a href="https://www.tiktok.com/@gorilla.boomin" target="_blank" rel="noopener">♪ TIKTOK</a><a href="https://www.facebook.com/GorillaBoomin" target="_blank" rel="noopener">f FACEBOOK</a><a href="https://www.twitch.tv/xgorillaboominxgaming" target="_blank" rel="noopener">◫ TWITCH / GAMING</a></div>`;const first=contact.querySelector(':scope > div');if(first)first.appendChild(links);}

  $$('.ecosystem-v51 a[data-group="social"]').forEach(a=>{const t=a.textContent.toLowerCase();if(t.includes('youtube')){a.href='https://www.youtube.com/@GorillaBoomin';a.target='_blank';a.rel='noopener'}else if(t.includes('instagram')){a.href='https://www.instagram.com/gorillaboomin';a.target='_blank';a.rel='noopener'}else if(t.includes('tiktok')){a.href='https://www.tiktok.com/@gorilla.boomin';a.target='_blank';a.rel='noopener'}else if(t.includes('twitch')){a.href='https://www.twitch.tv/xgorillaboominxgaming';a.target='_blank';a.rel='noopener'}});

  ['worlds','music','studio','mediahub','story','media','network'].forEach(id=>{const el=document.getElementById(id);if(el)el.classList.add('festival-section');});
})();